project:
  type: website
  output-dir: _site

website:
  title: "quarto-playground"
  cookie-consent:
    type: express
  page-footer:
    left: "Copyright 2025, ginatheducky"
    right:
      - text: Privacy Policy
        href: privacy-policy.qmd
      - text: License
        href: license.qmd
  navbar:
    right:
      - text: Home
        href: index.qmd
      - text: Blog
        href: blog.qmd
      - text: About
        href: about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
      - custom.scss
    css: styles.css
    toc: true
    html-math-method: mathml

execute:
  freeze: auto



