project:
  type: website
  output-dir: docs

website:
  title: "quarto-playground"
  page-footer:
    left: "Copyright 2025, ginatheducky"
    right:
      - text: Privacy Policy
        href: privacy-policy.qmd
      - text: License
        href: license.qmd
  navbar:
    right:
      - text: Home
        href: index.qmd
      - text: Blog
        href: blog.qmd
      - text: About
        href: about.qmd

format:
  html:
    theme: [custom.scss, cosmo]
    css: styles.css
    toc: true

execute:
  freeze: auto



